skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "WGR3TkneAhURGhPTLqS1TKejNWDQYAQu3QaMDiF4i5b"

[programs.devnet]
escrow = "WGR3TkneAhURGhPTLqS1TKejNWDQYAQu3QaMDiF4i5b"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"

[hooks]
